workflow revert

diff --git a/.github/workflows/R-CMD-check.yaml b/.github/workflows/R-CMD-check.yaml
--- a/.github/workflows/R-CMD-check.yaml
+++ b/.github/workflows/R-CMD-check.yaml
@@ -21,26 +21,18 @@ jobs:
   pre-check:
     runs-on: ubuntu-latest
     steps:
-      - name: Get User Permission
-        id: checkAccess
-        uses: actions-cool/check-user-permission@v2
-        with:
-          require: write
-          username: ${{ github.triggering_actor }}
-        env:
-          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
-      - name: Check User Permission
-        if: steps.checkAccess.outputs.require-result == 'false'
+      - name: Confirm crew102 triggered the build
         run: |
-          echo "${{ github.triggering_actor }} does not have permissions on this repo."
-          echo "Current permission level is ${{ steps.checkAccess.outputs.user-permission }}"
-          echo "Job originally triggered by ${{ github.actor }}"
-          exit 1
+          if [ "${{ github.event.sender.login }}" == "crew102" ]; then
+            echo "Actor is crew102"
+          else
+            echo "Actor is ${{ github.actor }}, failing build."
+            exit 1
+          fi
 
   R-CMD-check:
     needs: [pre-check]
     runs-on: ${{ matrix.config.os }}
-    timeout-minutes: 60
 
     name: ${{ matrix.config.os }} (${{ matrix.config.r }})
 
@@ -69,23 +61,11 @@ jobs:
           # Use the head SHA for pull requests
           ref: ${{ github.event.pull_request.head.sha || github.sha }}
 
-      - uses: r-lib/actions/setup-r@v2
+      - uses: r-lib/actions/setup-r@v1
         with:
           r-version: ${{ matrix.config.r }}
 
-      - uses: r-lib/actions/setup-pandoc@v2
-
-      - name: Check Secrets Access
-        if: ${{ env.PATENTSVIEW_API_KEY == '' }}
-        run: |
-          echo "No access to secrets"
-          exit 1
-
-      - name: Check Secrets Access
-        if: ${{ env.PATENTSVIEW_API_KEY == '' }}
-        run: |
-          echo "No access to secrets"
-          exit 1
+      - uses: r-lib/actions/setup-pandoc@v1
 
       - name: Query dependencies
         run: |
@@ -96,7 +76,7 @@ jobs:
 
       - name: Restore R package cache
         if: runner.os != 'Windows'
-        uses: actions/cache@v4
+        uses: actions/cache@v2
         with:
           path: ${{ env.R_LIBS_USER }}
           key: ${{ runner.os }}-${{ hashFiles('.github/R-version') }}-1-${{ hashFiles('.github/depends.Rds') }}
@@ -120,7 +100,6 @@ jobs:
       - name: Check
         env:
           _R_CHECK_CRAN_INCOMING_REMOTE_: false
-
         run: |
           options(crayon.enabled = TRUE)
           rcmdcheck::rcmdcheck(args = c("--no-manual", "--as-cran"), error_on = "warning", check_dir = "check")
@@ -129,7 +108,6 @@ jobs:
       - name: Run examples
         env:
           _R_CHECK_CRAN_INCOMING_REMOTE_: false
-
         run: |
           options(crayon.enabled = TRUE)
           remotes::install_cran("devtools")
